<!DOCTYPE html>
<html lang="pt-BR">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
        <meta name="description" content="Phalcon Skeleton for simple Phalcon applications">
        <meta name="author" content="Mateus Schmitz">
        <link rel="icon" href="/favicon.ico">

        <title>Phalcon Simple Skeleton</title>

        <!-- Bootstrap core CSS and Custom styles for this template-->
        <?php
            $this->assets->addCss('css/bootstrap.min.css')
                         ->addCss('css/sticky-footer-navbar.css')
                         ->outputCss();
        ?>

        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
        <!--[if lt IE 9]>
            <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
            <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
    </head>

    <body>
        <!-- Fixed navbar -->
        <nav class="navbar navbar-default navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="/">Phalcon Simple Skeleton</a>
                </div>
                <div id="navbar" class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li><a href="/">Home</a></li>
                        <li><a href="/about">About</a></li>
                        <li><a href="/">Contact</a></li>
                        <li><a href="https://github.com/mateuschmitz/phalcon-simple-skeleton" target="_blank">GitHub</a></li>
                </div><!--/.nav-collapse -->
            </div>
        </nav>

        <!-- Begin page content -->
        <?php 
            echo $this->getContent(); 
        ?>

        <footer class="footer">
            <div class="container">
                <p class="text-muted">2015 - <?php echo date('Y'); ?> Phalcon Simple Skeleton</p>
            </div>
        </footer>

        <!-- Bootstrap core JavaScript, JQuery and Hacks
        ================================================== -->
        <?php
            $this->assets->addJs('js/jquery-2.1.4.min.js')
                         ->addJs('js/bootstrap.min.js')
                         ->addJs('js/ie10-viewport-bug-workaround.js')
                         ->outputJs();
        ?>
    </body>
</html>
