<div class="container">
    <h1>About Phalcon Simple Skeleton</h1>

    <ul>
        <li>Requirements</li>
        <li>Includes
            <ul>
                <li>Gulp</li>
                <li>Bootstrap</li>
            </ul>
        </li>
        <li>Routes</li>
        <li>Controllers</li>
        <li>Actions</li>
        <li>Views</li>
        <li>Databases</li>
        <li>Extras
            <ul>
                <li>Composer</li>
                <li>PHPUnit</li>
                <li>Whoops</li>
            </ul>
        </li>
    </ul>

</div>