<div class="container">
    <div class="jumbotron">
        <div class="container">
            <h1>Phalcon Simple Skeleton!</h1>
            <p>This is a skeleton for Phalcon applications. The objective is to be simple, very simple and allowing the construction of an application fast.</p>
            <p><a class="btn btn-primary btn-lg" href="/about" role="button">Learn more &raquo;</a></p>
        </div>
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col-md-4">
            <h2>Documentation</h2>
            <p>The documentation is very simple and easy with new developers.</p>
            <p><a class="btn btn-default" href="https://docs.phalconphp.com/en/latest/index.html" target="_blank" role="button">Learn more &raquo;</a></p>
        </div>
        <div class="col-md-4">
            <h2>Forum</h2>
            <p>When you have questions, ask in forum to obtain support of the developers around the world.</p>
            <p><a class="btn btn-default" href="https://forum.phalconphp.com/" target="_blank" role="button">Learn more &raquo;</a></p>
        </div>
        <div class="col-md-4">
            <h2>Resources</h2>
            <p>Resources developed by community are available on Phalconist.</p>
            <p><a class="btn btn-default" href="https://phalconist.com/" target="_blank" role="button">Learn more &raquo;</a></p>
        </div>
        <div class="col-md-4">
            <h2>Phalcon Blog</h2>
            <p>News and updates are published first here.</p>
            <p><a class="btn btn-default" href="https://blog.phalconphp.com/" target="_blank" role="button">Learn more &raquo;</a></p>
        </div>
        <div class="col-md-4">
            <h2>About Phalcon</h2>
            <p>Learn more about Phalcon, team, evangelism, sponsors, how to contribute and more.</p>
            <p><a class="btn btn-default" href="https://phalconphp.com/en/about" target="_blank" role="button">Learn more &raquo;</a></p>
        </div>
        <div class="col-md-4">
            <h2>API DOC</h2>
            <p>All class and methods available on Phalcon are documented here. Enjoy.</p>
            <p><a class="btn btn-default" href="https://api.phalconphp.com/" target="_blank" role="button">Learn more &raquo;</a></p>
        </div>
    </div>
    <hr>
</div>